sudo: required

language: clojure

services:
  - docker

script:
  - lein test
  - docker-compose up --exit-code-from headless

deploy:
  provider: pages
  local-dir: autobahn/reports
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # From travis-ci.org repository settings
  verbose: treut
