version: "3"
services:
  autobahn-server:
    image: crossbario/autobahn-testsuite
    volumes:
      - ./autobahn/server.json:/config/fuzzingserver.json
      - ./autobahn/reports:/reports
    expose:
      - "9001"
  headless:
    image: clojure:alpine
    volumes:
      - .:/usr/src/headless
    working_dir: /usr/src/headless
    command: lein run -m headless.integration-test "autobahn-server"
    depends_on:
      - autobahn-server
